# Generated by Django 5.1.1 on 2025-01-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
